import{a as g,S as y,i as n}from"./assets/vendor-CIF6YjI2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))u(o);new MutationObserver(o=>{for(const a of o)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function e(o){const a={};return o.integrity&&(a.integrity=o.integrity),o.referrerPolicy&&(a.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?a.credentials="include":o.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function u(o){if(o.ep)return;o.ep=!0;const a=e(o);fetch(o.href,a)}})();const h="56104440-fcdbabdb32ae6a10913613c12",L="https://pixabay.com/api/",d=15;async function b(r,t=1){return(await g.get(L,{params:{key:h,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:d,page:t}})).data}const s={galleryContainer:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreButton:document.querySelector(".load-more-btn")},w=new y(".gallery a",{captionsData:"alt",captionDelay:250});function M(){s.loader&&s.loader.classList.remove("is-hidden")}function S(){s.loader&&s.loader.classList.add("is-hidden")}function q(r){const t=r.map(e=>`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-image"/>
      </a>
      <ul class="image-info">
        <li><p class="image-info-label">Likes</p> <p>${e.likes}</p></li>
        <li><p class="image-info-label">Views</p> <p>${e.views}</p></li>
        <li><p class="image-info-label">Comments</p> <p>${e.comments}</p></li>
        <li><p class="image-info-label">Downloads</p> <p>${e.downloads}</p></li>

      </ul>
    </li>
  `).join("");s.galleryContainer.insertAdjacentHTML("beforeend",t),w.refresh()}function B(){s.galleryContainer.innerHTML=""}function P(){s.loadMoreButton.classList.remove("is-hidden")}function f(){s.loadMoreButton.classList.add("is-hidden")}const c={form:document.querySelector(".form"),loadMoreButton:document.querySelector(".load-more-btn")};let p="",i=1;async function m(r,t=1){M(),f();try{const e=await b(r,t);if(e.hits.length===0){n.error({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}else return q(e.hits),E(e.totalHits,d)?P():n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),e.hits.length}catch(e){n.error({title:"Error",message:`Failed to fetch images with the ${e}. Please try again later.`,position:"topRight"})}finally{S()}}async function R(r){r.preventDefault(),B(),f();const t=r.target.elements["search-text"].value.trim();p=t,t?(i=1,await m(t,i),c.form.reset()):n.warning({title:"Empty Query",message:"Please enter a search query.",position:"topRight"})}async function v(){if(i+=1,await m(p,i)){const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}function E(r,t){const e=Math.ceil(r/t);return i<e}c.form.addEventListener("submit",R);c.loadMoreButton.addEventListener("click",v);
//# sourceMappingURL=index.js.map
